# Конфигурация моделирования
simulation:
  time_step: 1  # шаг моделирования в секундах
  duration: 100    # общая продолжительность моделирования в секундах

# Конфигурация воздушной обстановки
air_environment:
  id: 1
  position: [0.0, 0.0, 0.0]
  targets:
    - type: "AIR_PLANE"
      position: [5000.0, 5000.0, 2000.0]
      velocity: [100.0, 0.0, 0.0]
      id: 100
    - type: "HELICOPTER"
      position: [3000.0, 4000.0, 500.0]
      velocity: [50.0, -20.0, 0.0]
      id: 101

# Пункт боевого управления
combat_control_point:
  id: 0
  # Ссылки на пусковые установки, которые будет контролировать ПБУ
  missile_launcher_ids: [3, 4]
  # Ссылки на радары, которые будет использовать ПБУ
  radar_ids: [5, 6]

# Пусковые установки
missile_launchers:
  - id: 3
    position: [500.0, 500.0, 0.0]
    max_missiles: 5
    missiles:
      - id: 10
        velocity: 1000
        life_time: 60
        explosion_radius: 50
      - id: 11
        velocity: 1200
        life_time: 45
        explosion_radius: 40
  - id: 4
    position: [-500.0, -500.0, 0.0]
    max_missiles: 3
    missiles:
      - id: 12
        velocity: 1100
        life_time: 50
        explosion_radius: 45

# Радары
radars:
  - id: 5
    position: [0.0, 0.0, 20.0]
    azimuth_start: 0.0
    elevation_start: 0.0
    max_distance: 100000.0
    azimuth_range: 360.0
    elevation_range: 180.0
    azimuth_speed: 0.0
    elevation_speed: 0.0
    scan_mode: "horizontal"
  - id: 6
    position: [1000.0, 1000.0, 20.0]
    azimuth_start: 0.0
    elevation_start: 0.0
    max_distance: 100000.0
    azimuth_range: 360.0
    elevation_range: 180.0
    azimuth_speed: 0.0
    elevation_speed: 0.0
    scan_mode: "vertical"
